linter fix
Obimbo07/Portfolio pull request #12
Opened 2023-05-22 10:52 UTC by Obimbo07

Here i am updating my html css linters

2023-05-23 10:43 UTC, wayungi reviewed
Hi @Obimbo07 , 
![image](https://user-images.githubusercontent.com/99656687/224543512-ddbefa59-dc68-47c2-b7fe-f55acdacd3eb.png)

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ❌ ❌ 

- [ ] You have submitted a project that does have your partner's contribution.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-24 00:22 UTC, omar-muhamad requested changes
# Changes Required ♻️
### Hi Team,

### Nice job, you are almost there.

![cat-driving-serious](https://user-images.githubusercontent.com/68796232/223284600-852bcd90-1495-4a40-8515-cc12636b369b.gif)

## (Highlights) Good Points: :+1:
- Your work is well documented. ✔
- The correct workflow is used.  ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- [ ] Please check the inline comments below ⬇️.

## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-05-24 00:22 UTC, Omar-Muhamad commented on index.html
> +            </ul>
- [ ] Kindly use the correct close button logo by making it smaller and choosing the correct icon to match the given design.
- [ ] Please remove the link staying for the mobile menu options. you can use CSS property `text-decoration: none;`

| Given Design  | Your Design |
| ------------- | ------------- |
| ![image](https://github.com/Obimbo07/Portfolio/assets/68796232/964c1f20-e311-4d5e-86bc-3dedb82cb7b9)  | ![image](https://github.com/Obimbo07/Portfolio/assets/68796232/45f680ff-cb39-45d5-b7b6-d5235cd3bc4f)  |

2023-05-26 20:40 UTC, Kamba56 commented
Hi @Obimbo07

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that **is not meant for this milestone**. This PR is meant for the Moblie menu milestone and you submitted it for the Pop up milestone. Kindly submit the right PR.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-26 20:50 UTC, merged