Contact form and mobile updates
Obimbo07/Portfolio pull request #3
Opened 2023-05-10 13:21 UTC by Obimbo07

This branch introduces the following updates:
1. Contact form section and updates 
2. finish the mobile design and layout

2023-05-10 13:29 UTC, zieeco requested changes
Hi @Team,

<img height="220" src="https://media1.giphy.com/media/Cm9wKmKMUlRPvdoHgU/giphy-downsized-medium.gif"/>

Great job so far! 👏 
You've done well, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- No linter errors.✔️
- Nice design. ✔️
- Descriptive PR. ✔️


## Required Changes ♻️
_Check the comments under the review._




## Optional suggestions
_Check the comments under the review._

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-10 13:29 UTC, zieeco commented on styles.css
> +
- Hey, please, let's improve on our design to match the Figma as much as we can to make your design consistent with the main design from the Figma:

*Your design*
![image](https://github.com/Obimbo07/Portfolio-mobileFirst/assets/59397159/b1295f3a-1a95-47ec-b57f-46b09676466c)

*Figma design*
![image](https://github.com/Obimbo07/Portfolio-mobileFirst/assets/59397159/364bb964-c4e3-4449-88a5-96ff1d7a92cb)

2023-05-10 15:18 UTC, Shisui6 requested changes
Hi @Obimbo07, 

# Requires Changes 🍀
Great work on making the changes requested by a previous reviewer 👍
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet🪲.


 ## Highlights 🎯
 - Form includes validations ✅


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions 🪶

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were simply missed by the previous reviewer, and addressing them will really improve your application._

You can also consider the following:

N/A

Cheers and Happy coding!🍻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid, unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-10 15:18 UTC, Shisui6 commented on index.html
> +        <form action="https://formspree.io/html" method="post">
[Optional] This is one of the project requirements but was missed by the previous reviewer so I highly encourage you to implement it.

- Please make sure that your form connects to the formspree service by attaching a valid form id to the URL

2023-05-10 15:18 UTC, Shisui6 commented on index.html
> +          <textarea name="" id="mess" placeholder="Write me something..." cols="50" rows="10" maxlength="500"></textarea>
[Optional] This is one of the project requirements but was missed by the previous reviewer so I highly encourage you to implement it.

- Please make sure that the user cannot submit the form without entering a message in the textarea

2023-05-10 15:18 UTC, Shisui6 commented on styles.css
> +}
As the previous reviewer suggested, your contact form could still use some work to adhere to the figma design

Your design:
<img width="239" alt="image" src="https://github.com/Obimbo07/Portfolio-mobileFirst/assets/37116322/3b682147-80e5-492f-b3f5-24b104dd3b11">

Figma design:
<img width="177" alt="image" src="https://github.com/Obimbo07/Portfolio-mobileFirst/assets/37116322/714df73d-c4e3-4a37-b565-63ad1ddc3b39">

A few things to note:
- The main issue here is that you are using absolute positioning on your sections and a top offset to place the different sections on the page. Please note that this is an incorrect implementation because it doesn't allow your design to be responsive and will cause your design to be different on different screen sizes. I would suggest you update your stylesheet to not use absolute positioning and instead place each section on top of each other using the correct heights, margins and padding to achieve the desired design. This may take some time and experimentation, so I encourage you to take your time with this👍
- Please also make sure your form elements are styled according to the figma design using the correct margins padding and colors
- Please update the color of your social icons to match the figma design
- Please make sure the submit button is properly centered and the divider at the bottom of the page stretches across the entire width of the page

2023-05-11 10:47 UTC, NahnahAJ requested changes
## Project Status: CHANGES REQUIRED :recycle: 
Hi @Obimbo07 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which haven't been addressed yet.
<img src="https://media3.giphy.com/media/VlqzeaRnhCvPLfrSh6/giphy.gif"/>

 ## Highlights
- No linter errors :heavy_check_mark: 
- Good use of GitHub flow :heavy_check_mark: 
- Nice Design :heavy_check_mark:  

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @NahnahAJ in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-11 10:47 UTC, NahnahAJ commented on index2.html
> +            <textarea name="" id="mess" placeholder="Write me something..." cols="50" rows="10" maxlength="500"></textarea>
- [ ] Great job @Obimbo07 Your project looks good there are just a few style changes that the previous reviewer mentioned which haven't yet been implemented. :+1: 
- [ ] First of all, the previous reviewer mentioned that you style the input elements as seen in the Figma design but currently, you have a border around the textarea which wasn't present in the original design so kindly remove it :+1: 
- Your Design
![image](https://github.com/Obimbo07/Portfolio-mobileFirst/assets/102699958/d8cfc5dd-5829-466b-817e-118a23a420ea)

- The Figma Design
![image](https://github.com/Obimbo07/Portfolio-mobileFirst/assets/102699958/a7124c87-43ef-4c8a-9844-6d93380b267e)

2023-05-11 10:47 UTC, NahnahAJ commented on index2.html
> +        <hr class="form-breaker">
- [ ] The previous reviewer also mentioned that the `horizontal line` needs to extend across the entire width of the page as seen in the original design :wink: 
- Your Design
![image](https://github.com/Obimbo07/Portfolio-mobileFirst/assets/102699958/c5698278-2be8-47ed-a82e-7c6dde2d0fae)

- The Figma Design
![image](https://github.com/Obimbo07/Portfolio-mobileFirst/assets/102699958/a93ffd5b-0fac-4cbe-8e4d-5ee2356f35e8)

2023-05-11 10:47 UTC, NahnahAJ commented on index2.html
> +            </ul>
- [ ] Lastly, just as the previous reviewer mentioned, please ensure that your `social icons` have the same colors as seen in the Figma design :wink: 
- Your Design
![image](https://github.com/Obimbo07/Portfolio-mobileFirst/assets/102699958/1f3950c8-7279-4d67-a11a-dbe05d2a723b)

- The Figma Design
![image](https://github.com/Obimbo07/Portfolio-mobileFirst/assets/102699958/102e5796-a976-4e49-bdda-dedabe62b66c)

2023-05-11 13:51 UTC, Efiamotu-1 approved these changes
Hi @Obimbo07, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# STATUS: APPROVED 🕺🥳 

![giphy](https://user-images.githubusercontent.com/89055502/234114221-4ca295de-fd8f-4af6-9c49-a6d4c6ea67f7.gif)


## Highlights :dart: 
* Correct GitHub flow :heavy_check_mark: 
* All linters passing :heavy_check_mark: 
* Good PR  Title & summary :heavy_check_mark: 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, you can now Merge since it is Approved ✅, However if there are any conflicts please resolve them before merging.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@Efiamotu-1](https://img.shields.io/github/followers/Efiamotu-1?label=Habeeb-Efiamotu-Musa&style=social)](https://github.com/Efiamotu-1/)
- This is My **linkedIn**.[![Habeeb Efiamotu Musa](https://img.shields.io/badge/linkedin-@Habeeb-crimson)](https://www.linkedin.com/in/musa-habeeb/)
- This is My **Twitter**: [![@EFYAMOTU](https://img.shields.io/twitter/follow/omarramoun?label=Habeeb-Efiamotu-Musa&style=social)](https://twitter.com/EFYAMOTU)
- This is My **Slack**: [![Habeeb Efiamotu Musa ](https://img.shields.io/badge/slack-@Habeeb-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-11 14:43 UTC, merged